version: "3.8"

services:
  tests:
    build:
      context: .
      target: build
    command: "./gradlew cleanTest test --info"
    volumes:
      - "./build:/srv/demo-api/build"

  demo-api-jvm:
    build:
      context: .
      target: demo-api-jvm
    ports:
      - "8080:8080"

  demo-api-native:
    build:
      context: .
      target: demo-api-native
    ports:
      - "8080:8080"
