name: "demo-api development pipeline"

trigger:
  branches:
    exclude:
      - main
      - production
  paths:
    include:
      - 'src/'
      - 'build.gradle.kts'
      - 'settings.gradle.kts'
      - 'Dockerfile'
      - 'docker-compose.yml'
      - 'pipelines/demo-api-dev.yml'
      - 'pipelines/templates/demo-api-cd-template.yml'
      - 'pipelines/templates/demo-api-ci-template.yml'
    exclude:
      - '*'

pr: none

stages:
  - stage: CI
    displayName: 'Test'
    jobs:
      - template: '/pipelines/templates/demo-api-ci-template.yml'

  - stage: CD
    displayName: 'Deploy to dev'
    jobs:
      - template: '/pipelines/templates/demo-api-cd-template.yml'
        parameters:
          environmentId: 'dev'
