name: "demo-api production pipeline"

trigger:
  branches:
    include:
      - production
    exclude:
      - '*'
  paths:
    include:
      - 'Dockerfile'
      - 'build.gradle.kts'
      - 'docker-compose.yml'
      - 'pipelines/demo-api-dev.yml'
      - 'pipelines/templates/demo-api-cd-template.yml'
      - 'settings.gradle.kts'
      - 'src/'
    exclude:
      - '*'

pr: none

stages:
  - stage: CD
    displayName: 'Deploy to prd'
    jobs:
      - template: '/pipelines/templates/demo-api-cd-template.yml'
        parameters:
          environmentId: 'prd'
