name: "demo-api development pipeline"

pr:
  autoCancel: false
  drafts: false
  branches:
    exclude:
      - main
      - production
  paths:
    include:
      - /src
      - /Dockerfile
      - /*.kts
      - /pipelines/demo-api-dev.yml
      - /pipelines/templates/demo-api-*.yml
    exclude:
      - '*'

trigger: none # to only trigger on PRs, not on push

stages:
  - stage: CI
    displayName: 'Test'
    jobs:
      - template: '/pipelines/templates/demo-api-ci-template.yml'

  - stage: CD
    displayName: 'Deploy to dev'
    jobs:
      - template: '/pipelines/templates/demo-api-cd-template.yml'
        parameters:
          environmentId: 'dev'
