name: "demo-api staging pipeline"

trigger: none
pr: none

stages:
  - stage: CI
    displayName: 'Test'
    jobs:
      - template: '/pipelines/templates/demo-api-ci-template.yml'

  - stage: CD
    displayName: 'Deploy to stg'
    jobs:
      - template: '/pipelines/templates/demo-api-cd-template.yml'
        parameters:
          environmentId: 'stg'
