name: "demo-api production pipeline"

trigger: none
pr: none

stages:
  - stage: CD
    displayName: 'Deploy to prd'
    jobs:
      - template: '/pipelines/templates/demo-api-cd-template.yml'
        parameters:
          environmentId: 'prd'
