name: "Production infrastructure pipeline"

# This pipeline must be manually triggered
pr: none
trigger: none

stages:
  - template: '/pipelines/infra-template.yml'
    parameters:
      environmentId: 'prd'
